[tool.poetry]
name = "agent-backend"
version = "0.1.0"
description = ""
authors = ["ragy abraham <ragy@rna.digital>"]
readme = "README.md"
packages = [{include = "agent-backend"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

autogen = { git = "https://github.com/rnadigital/autogen.git", branch = "docker-function-execution" }
#autogen = { git = "https://github.com/rnadigital/autogen.git", tag = "v0.2.8" }
fastapi = "^0.103.2"
uvicorn = "^0.23.2"
python-dotenv = "^1.0.0"
pymongo = "^4.5.0"
redis = "<5.0.0"
termcolor = "^2.3.0"
python-socketio = "5.10.0"
websocket-client = "^1.6.4"
bullmq = "^1.15.4"
openai = "^1.3.6"
diskcache = "^5.6.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
